print("Juan Gabriel Lopez")
print("Axel David Rodriguez Prado")
print("Daniela Aracely Rodriguez Renteria")
print("Angie Sarahi Camarillo Ramirez")
print("Linus Torvalds")
print("Daira Yllen Torres Gonzalez")
print("Johan Alexis Balleza Rangel")